# See here for tags: https://hub.docker.com/_/microsoft-powershell
ARG VARIANT="7.2.0-windowsservercore-20h2"
FROM mcr.microsoft.com/powershell:${VARIANT}

# As we're only using this for testing purposes this should be fine
USER ContainerAdministrator