---
# This will build and test the module on the various operating systems we support
name: test
on: 
  pull_request:
    
jobs:
  build-and-test:
    runs-on: ${{matrix.os}}
    strategy:
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: checkout-module
        uses: actions/checkout@v2
        with: 
          path: Brownserve.BuildTools
      - name: run-build-script
        shell: pwsh
        run: |
            ./Brownserve.BuildTools/.build/build.ps1 -BranchName $env:GITHUB_REF -Verbose
  